# Required

[[plugins]]
repo = 'Shougo/dein.vim'

# Colorschemes

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

# Filetypes

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'

# functions
[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = "autozimu/LanguageClient-neovim"
build = "bash install.sh"
