# Required

[[plugins]]
repo = 'Shougo/dein.vim'

# Colorschemes

[[plugins]]
repo = 'altercation/vim-colors-solarized'

# Filetypes

[[plugins]]
repo = 'dag/vim2hs'

[[plugins]]
repo = 'cespare/vim-toml'

# functions

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
