# Required

[[plugins]]
repo = 'Shougo/denite.nvim'

# Filetypes

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

# General

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_i = 1

# IDE features

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
on_ft = ['rust', 'c', 'cpp']
on_i = 1

[[plugins]]
repo = "autozimu/LanguageClient-neovim"
rev = "next"
build = "bash install.sh"
hook_add = '''
set hidden
let g:LanguageClient_diagnosticsSignsMax = 2
set signcolumn=yes
nnoremap <F5> :call LanguageClient_contextMenu()<CR>
'''
on_ft = ['rust', 'c', 'cpp']

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
on_ft = ['html']

# Operators
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']
on_i = 1

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'
on_i = 1

