# Required

[[plugins]]
repo = 'Shougo/dein.vim'

# Colorschemes

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = '~/.fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
