# Filetypes

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'let-def/ocp-indent-vim'
on_ft = ['ocaml']

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']

[[plugins]]
repo = 'lifepillar/pgsql.vim'
hook_source = "let g:sql_type_default = 'pgsql'"
on_ft = ['sql']

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = ['blade']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'Shirk/vim-gas'
on_ft = ['asm']

# IDE features

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'ncm2/ncm2'
depends = ['nvim-yarp', 'ncm2-bufword']
hook_source = 'call kb10uy#plugin#setup_completion()'
# TODO: cpp を戻したい
on_ft = [
  'rust', 'c', 'cpp',
  'python',
  'ocaml', 'haskell',
  'javascript', 'typescript',
  'php', 'sql',
  'tex',
]

[[plugins]]
repo = 'ncm2/ncm2-bufword'

[[plugins]]
repo = "autozimu/LanguageClient-neovim"
rev = "next"
build = "bash install.sh"
hook_source = 'call kb10uy#plugin#setup_lsp()'
on_ft = [
  'rust', 'c', 'cpp',
  'python',
  'haskell',
  'javascript', 'typescript',
  'php',
]

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php']

[[plugins]]
repo = 'lervag/vimtex'
hook_source = 'call plugin#setup_tex()'
on_ft = ['tex']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_event = 'CursorHold'

# Operators

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']
on_event = 'InsertEnter'

# [[plugins]]
# repo = 'alpaca-tc/vim-endwise.git'
# on_event = 'InsertEnter'

