# Required

[[plugins]]
repo = 'Shougo/dein.vim'

# Colorschemes

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'junegunn/fzf'
build = './install'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
