# Filetypes

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'let-def/ocp-indent-vim'
on_ft = ['ocaml']

# General

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_event = 'InsertEnter'

# IDE features

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = 'call plugin#setup_completion()'
on_ft = ['rust', 'c', 'cpp', 'tex', 'ocaml', 'javascript', 'typescript', 'php', 'haskell']

[[plugins]]
repo = "autozimu/LanguageClient-neovim"
rev = "next"
build = "bash install.sh"
hook_source = 'call plugin#setup_lsp()'
on_ft = ['rust', 'c', 'cpp', 'javascript', 'typescript', 'php', 'haskell']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo = 'lervag/vimtex'
hook_source = 'call plugin#setup_tex()'
on_ft = ['tex']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_event = 'CursorHold'

# Operators

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']
on_event = 'InsertEnter'

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'
on_event = 'InsertEnter'

