alias ls='ls -F --color=auto'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias rm='rm -i'
alias rmrf='rm -rf'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias sudo='sudo '
alias -g L='| less'
alias -g G='| grep -a'
alias lgrep='ls -la | grep -P'
alias acurl='curl -H "X-Requested-With: XMLHttpRequest"'
alias lzrc="$VISUAL ~/.config/zsh/$HOST.zsh"
